"""currency, funds, sip plans

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 18:45:54.821021

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sip_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sip_plans_portfolio", "sip_plans", ["portfolio_id"], unique=False)
    op.add_column("assets", sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False))
    op.add_column("assets", sa.Column("exchange", sa.String(length=16), nullable=True))
    with op.batch_alter_table("transactions") as batch:
        batch.add_column(sa.Column("sip_plan_id", sa.Uuid(), nullable=True))
        batch.create_foreign_key(
            "fk_transactions_sip_plan_id", "sip_plans", ["sip_plan_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions") as batch:
        batch.drop_constraint("fk_transactions_sip_plan_id", type_="foreignkey")
        batch.drop_column("sip_plan_id")
    op.drop_index("ix_sip_plans_portfolio", table_name="sip_plans")
    op.drop_table("sip_plans")
    op.drop_column("assets", "exchange")
    op.drop_column("assets", "currency")
    # ### end Alembic commands ###
